### ISSUE TITLE
Fixed value is from example cert. Needs to go into inputs. Cert from DoD

### ISSUE THREAD

**Issue by jrmetzger** [mitre/redhat-enterprise-linux-9-stig-baseline#59]
https://github.com/mitre/redhat-enterprise-linux-9-stig-baseline/blob/1dee0651ae4621c41dfa689133f7c4bb3ae72e81/controls/SV-258131.rb#L78

Fixed value is from example cert. Needs to go into inputs. Cert from DoD

https://public.cyber.mil/pki-pke/pkipke-document-library/?_dl_facet_pkipke_type=popular-dod-certs

```
inputs:
  ...
  root_ca:
    description: Path to an accepted trust anchor certificate file (DoD)
    type: String
   value:
      root_ca_file: /etc/sssd/pki/sssd_auth_ca_db.pem
      root_ca_issuer: /C=US/O=U.S. Government/OU=DoD/OU=PKI/CN=DoD Root CA 6
      root_ca_subject: /C=US/O=U.S. Government/OU=DoD/OU=PKI/CN=DOD DERILITY CA-4
```
