### ISSUE TITLE
Platform Family Fix

### ISSUE THREAD

**Issue by wdower** [mitre/redhat-enterprise-linux-9-stig-baseline#74]
Right now this profile supports mainline RHEL9 only:

```
# inspec.yml
supports:
  - platform-name: redhat
    release: 9.*
```

This means the profile fails against other OSes in the same platform family as RHEL even though the STIG should still be applicable to them. We should switch `inspec.yml` to use `platform-family` instead.
